version: "3.8"

services:
  redis:
    image: redis:8.0.2-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    command: >
      redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru
    volumes:
      - ./data:/data
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis-data: